### ISSUE TITLE
classifier.py crashes at line 44

### ISSUE THREAD

**Issue by stefanobellelli** [stefanobellelli/nonce3vec#1]
Here's the culprit:

```python
43 #prepare train/test sets
44 x_train = concatenate([gen.train.vec, inf.train.vec])
45 x_test  = concatenate([gen.test.vec,  inf.test.vec])
```

Here's the error message:
```
Traceback (most recent call last):
  File "classifier.py", line 44, in <module>
    x_train = concatenate([gen.train.vec, inf.train.vec])
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
I suspect the error comes from the fact that the two files bear vectors of different length. This comes from the design choice of making a separate index of n-grams for each parsed source. A potential solution might be to check *both* sources, create one single index, and vectorialise both sources according to that index.

**Comment by stefanobellelli** [comment]
I've implemented my intuition in the branch `test`. Indeed, the code there doesn't show this bug apparently.
So, bug solved it seems?

**Comment by minimalparts** [comment]
Yes, this looks very good! Conceptually, think of the SVM drawing a boundary between classes within *one* space. That space has a certain number of dimensions, and so everything you do has to be expressed in terms of those dimensions.

When moving to real data, you'll probably want to keep a separate record of your dimensions. That is because you'll probably have too many to play with and you'll decide to only keep the ones corresponding to the n most frequent ngrams. So you may already want to setup your code to allow for that. (That would be in vectorizer.py.)

**Comment by stefanobellelli** [comment]
> you'll probably want to keep a separate record of your dimensions.
Can you be more specific?

In the logfiles there is currently:
- a count of all occurrences of all n-grams per each sentence (`unified_dictionary.log`, but also `dictionary.log` in the subdirs);
- a list of all n-grams that exist, in the same order as the vector dimensions (`unified_index.log`);
- the vectors themselves (`wordvec.log` & `posvec.log` in the subdirs, and also the pickled binaries).

Will I need some _other_ data that is not already there? Or just data that can be extracted from there?

**Comment by minimalparts** [comment]
Yes, sorry. You may already have this somewhere that I haven't looked at, but you should print out a raw frequency file for your ngrams (or pickle it if you prefer). I normally print things out in sorted order, highest frequencies at the top, but if you prefer you can do the sorting after loading the file. 

Basically, we want something like this (I'm making up the numbers):

    is_the 20456
    are_the 19567
    ...
    cat_of 1567
    ...
    aluminium_member 1

From this information, you may for instance decide to only keep the top 10000 bigrams as dimensions for your vector space. Then your vectors will be expressed in terms of those 10000 dimensions only, ignoring the rest. The idea is that when you read the info corresponding to your unified_dictionary.log (sorry, I haven't looked at your code in enough detail to know where that happens, but you'll get my gist) you only 'activate' the dimensions that are contained in your 10000D basis to create your vectors (e.g. the stuff in log/gen/posvec.log). We talked at some point about keeping a record of dimensions to their labels . That helps you create your vectors with only the correct dimensions. 

Example. Let's imagine you're only keeping 2 dimensions: _as_its_ and _also_known_. You have a dimension-to-label dictionary (let's call it _ngram-to-i_) that tells you the following:

_as_its_ --> 0
_also_known_ --> 1

(I.e. you get the index of the dimension that the bigram corresponds to.)

Now you want to express the following in your 2 dimensions:

"Senary": {
        "words": {
            "or_heximal": 1,
            "also_known": 1,
            "senary_numeral": 1,
            "the_senary": 1,
            "as_its": 1,
            "heximal_has": 1,
            "its_base": 1,
            "numeral_system": 1,
            "as_base-6": 1,
            "system_also": 1,
            "six_as": 1,
            "base-6_or": 1,
            "known_as": 1,
            "has_six": 1
        },

You go through this list of bigrams, checking whether it is in _ngram-to-i_. If yes, you activate the relevant dimension with the relevant frequency. For example:

_also_known_ is in _ngram-to-i_ at position 1, and has frequency 1 for "Senary", so I take my 2D vector for Senary, initialised to all zeros [0,0] and I change the value at position 1:

[0,0] becomes [0,1]

Does that make sense?

**Comment by minimalparts** [comment]
Btw, if we're going to discuss this further here, it might be better to open a new issue. Sorry, I should have done it...
